nelmio_api_doc:
    documentation:
        servers:
            - url: http://localhost:8000
              description: API over HTTP
        info:
            title: doc
            description: This is an awesome app!
            version: 1.0.0
            x-build: #CommitHash
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api # Accepts routes under /api except /api/doc
